general:
  http_port: 8000
  log_level: debug
  type: mqtt
  data_cache_sec: 600
  check_cache_interval: 10
  down_channel_size: 50
mysql:
  user: niu_sharing
  password: 3gnhbq6XUBctl5C5Pptfo4QYtsA6Y
  host: c01-ha.mysql.k8s.proxy.local
  port: 3306
  database: niu_sharing

mqtt:
  server: tcp://39.100.117.189:1883
  cleanSession: true
  eventTopic: gateway/+/+/event/+
  commandTopicTemplate: gateway/{{ .DevType }}/{{ .DevId }}/command/{{ .CommandType }}
  qos: 0
  username: ldm
  password: "123456"
  maxReconnectInterval: 1
  clientID: clould
  maxHandleGoroutine: 100

consul:
  server: 127.0.0.1:8500

