# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rgateway.proto\x12\x05proto\"\x86\x01\n\x0bUplinkFrame\x12\x11\n\tFrameType\x18\x01 \x01(\x05\x12\x0f\n\x07\x44\x65vName\x18\x02 \x01(\t\x12\r\n\x05\x44\x65vId\x18\x03 \x01(\t\x12\x10\n\x08\x46rameNum\x18\x04 \x01(\r\x12\x0c\n\x04Port\x18\x05 \x01(\r\x12\x12\n\nPhyPayload\x18\x06 \x01(\x0c\x12\x10\n\x08UplinkId\x18\x07 \x01(\r\"\x8a\x01\n\rDownlinkFrame\x12\x11\n\tFrameType\x18\x01 \x01(\x05\x12\x0f\n\x07\x44\x65vName\x18\x02 \x01(\t\x12\r\n\x05\x44\x65vId\x18\x03 \x01(\t\x12\x10\n\x08\x46rameNum\x18\x04 \x01(\r\x12\x0c\n\x04Port\x18\x05 \x01(\r\x12\x12\n\nPhyPayload\x18\x06 \x01(\x0c\x12\x12\n\nDownlinkId\x18\x07 \x01(\r\"1\n\x07Payload\x12\x0c\n\x04kind\x18\x01 \x01(\r\x12\x0b\n\x03key\x18\x02 \x01(\r\x12\x0b\n\x03val\x18\x03 \x01(\x0c*\x1f\n\x08\x43\x61tegory\x12\x07\n\x03\x43MD\x10\x00\x12\n\n\x06\x43ONFIG\x10\x01*\x1e\n\x06\x44\x65vice\x12\x08\n\x04LAMP\x10\x00\x12\n\n\x06HEATER\x10\x01*\x1c\n\tOperation\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x62\x06proto3')
)

_CATEGORY = _descriptor.EnumDescriptor(
  name='Category',
  full_name='proto.Category',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIG', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=353,
  serialized_end=384,
)
_sym_db.RegisterEnumDescriptor(_CATEGORY)

Category = enum_type_wrapper.EnumTypeWrapper(_CATEGORY)
_DEVICE = _descriptor.EnumDescriptor(
  name='Device',
  full_name='proto.Device',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LAMP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEATER', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=386,
  serialized_end=416,
)
_sym_db.RegisterEnumDescriptor(_DEVICE)

Device = enum_type_wrapper.EnumTypeWrapper(_DEVICE)
_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='proto.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=418,
  serialized_end=446,
)
_sym_db.RegisterEnumDescriptor(_OPERATION)

Operation = enum_type_wrapper.EnumTypeWrapper(_OPERATION)
CMD = 0
CONFIG = 1
LAMP = 0
HEATER = 1
OFF = 0
ON = 1



_UPLINKFRAME = _descriptor.Descriptor(
  name='UplinkFrame',
  full_name='proto.UplinkFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FrameType', full_name='proto.UplinkFrame.FrameType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DevName', full_name='proto.UplinkFrame.DevName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DevId', full_name='proto.UplinkFrame.DevId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FrameNum', full_name='proto.UplinkFrame.FrameNum', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Port', full_name='proto.UplinkFrame.Port', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PhyPayload', full_name='proto.UplinkFrame.PhyPayload', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UplinkId', full_name='proto.UplinkFrame.UplinkId', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=159,
)


_DOWNLINKFRAME = _descriptor.Descriptor(
  name='DownlinkFrame',
  full_name='proto.DownlinkFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FrameType', full_name='proto.DownlinkFrame.FrameType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DevName', full_name='proto.DownlinkFrame.DevName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DevId', full_name='proto.DownlinkFrame.DevId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FrameNum', full_name='proto.DownlinkFrame.FrameNum', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Port', full_name='proto.DownlinkFrame.Port', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PhyPayload', full_name='proto.DownlinkFrame.PhyPayload', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DownlinkId', full_name='proto.DownlinkFrame.DownlinkId', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=300,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='proto.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='proto.Payload.kind', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.Payload.key', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val', full_name='proto.Payload.val', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=351,
)

DESCRIPTOR.message_types_by_name['UplinkFrame'] = _UPLINKFRAME
DESCRIPTOR.message_types_by_name['DownlinkFrame'] = _DOWNLINKFRAME
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.enum_types_by_name['Category'] = _CATEGORY
DESCRIPTOR.enum_types_by_name['Device'] = _DEVICE
DESCRIPTOR.enum_types_by_name['Operation'] = _OPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UplinkFrame = _reflection.GeneratedProtocolMessageType('UplinkFrame', (_message.Message,), {
  'DESCRIPTOR' : _UPLINKFRAME,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:proto.UplinkFrame)
  })
_sym_db.RegisterMessage(UplinkFrame)

DownlinkFrame = _reflection.GeneratedProtocolMessageType('DownlinkFrame', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLINKFRAME,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:proto.DownlinkFrame)
  })
_sym_db.RegisterMessage(DownlinkFrame)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:proto.Payload)
  })
_sym_db.RegisterMessage(Payload)


# @@protoc_insertion_point(module_scope)
